# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ContactList' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ContactList
    pod 'SQLite.swift', '~> 0.12.0'

  target 'ContactListTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ContactListUITests' do
    # Pods for testing
  end

end
